### ISSUE TITLE
More Robust Makefile Targets

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#1027]
Acceptance Criteria

Ensure that makefile targets can be executed successfully from each directory (without broken path problems)

**Comment by SebieF** [comment]
A minor comment here (I am not entirely sure if this belongs directly to this issue): When I have a `kind` cluster with a different name (for example: scb), kind related make targets will fail, e.g.:
```bash
common-kind-import:
	@echo ".: 💾 Importing the image archive '$(module)-$(name).tar' to local kind cluster."
	kind load image-archive ./$(module)-$(name).tar  #fix: --name scb
```
I think it is the only affected make-target.

**Comment by Weltraumschaf** [comment]
I'll recommend to file a separate issue for that.

**Comment by the-simmon** [comment]
To run a makefile from a different directory one has to specify the path to the makefile `make -f path/to/makefile target`. This would not work in our project because of the relative paths in our makefiles.

Make actually has an option to change the working directory of make: `make -C path/to/workingDir target`. This command can also be combined with `-f` to specify the makefile. Keep in mind that `-f` then starts in the working directory specified with `-C` and not in the directory of your shell.
With the `-C` option it is possible to run our makefiles from any directory even though there are relative paths in our makefiles.
