### ISSUE TITLE
Require managed-by label in Service autodiscovery

### ISSUE THREAD

**Issue by the-simmon** [secureCodeBox/secureCodeBox#1194]
The service autodiscovery checks if a scan already exists by checking if a scan with certain labels exists. The `managed-by` label was not added to those scans initially. Because of this the service autodiscovery can not assume that all scans have this label (when a scan was created before the `managed-by` label was added. Newer scans have the `managed-by` label).  This makes the code a bit hard to read, as the autodiscovery is querying a scan with certain labels, just to add the `managed-by` label after that.
https://github.com/secureCodeBox/secureCodeBox/blob/102d8bf152ea9c96ae82af9a63106f47cef2a288/auto-discovery/kubernetes/controllers/service_scan_controller.go#L123-L129
https://github.com/secureCodeBox/secureCodeBox/blob/102d8bf152ea9c96ae82af9a63106f47cef2a288/auto-discovery/kubernetes/controllers/service_scan_controller.go#L158-L159
This could be changed with a breaking change. The service autodiscovery could assume that every scan has the manged-by label. This would be a minor code readability improvement. It would not change the behavior of the service autodiscovery.

**Comment by malexmave** [comment]
Note that at the moment, at least in my cluster, the label is `app.kubernetes.io/managed-by=securecodebox` (not `securecodebox-autodiscovery`), and it seems to only be applied to scanners, not parsers. The label seems to be [applied in the operator](https://github.com/secureCodeBox/secureCodeBox/blob/9f9898f0f730f31ea868db4b6ce2b0f894ab3334/operator/controllers/execution/scans/scan_reconciler.go#L193).

=> are we certain that the code you link above is even running properly, and not overwritten by the operator?
=> We should ensure that the label is also applied to parsers, not just scanners.

Or am I misunderstanding what this issue is referring to? (In which case I will open a new issue about the discrepancy between scanners and parsers in labeling - and I am not sure if hooks are labelled correctly, either, as I did not test that yet).

**Comment by rseedorff** [comment]
@the-simmon can you help to improve the issue description here?

**Comment by the-simmon** [comment]
I edited the initial ticket to make it clearer.
