### ISSUE TITLE
Label Selectors for ScanCompletionHooks

### ISSUE THREAD

**Issue by huongkieutiki** [secureCodeBox/secureCodeBox#1226]
I want to config special hooks for each scantype.

For example: If I use wpscan scantype, after parser finished, it will call only notification-webhook, and if we use zap, it will call defectdojo. 

How can I do to get it?
Thank all!

**Comment by J12934** [comment]
Hi @huongkieutiki 👋

At the moment that is not directly possible, but would be definitely helpful.
I think we had this asked before so I'll change this to a feature request so that we this will get implemented when somebody finds the time and picks this up.

Best workaround for the time being is to separate the scans out into two namespace and install the defectdojo hook in one and the notification hook in the other.

**Comment by J12934** [comment]
@huongkieutiki oh ups, forgot that it acutally was already implemented 😅

See hook selectors: https://docs.securecodebox.io/docs/api/crds/scan#hookselector-optional

**Comment by huongkieutiki** [comment]
@J12934 J thank you very much!
