### ISSUE TITLE
Make use of makefile in install.sh

### ISSUE THREAD

**Issue by Ilyesbdlala** [secureCodeBox/secureCodeBox#1278]
### Is your feature request related to a problem?

After #1282 The install.sh now installs the remote version of SCB that describes the latest release.
Installing the local development version is not possible.

### Describe the solution you'd like

Add makefile functionalities to the install.sh script, instead of explicitly installing helm charts. This can enabled through a flag that either installs the remote version or uses makefiles to install the local version.
### Additional context

Installing local helm charts is no longer possible without the makefiles. That is, since we no longer push current development Docker images to DockerHub.
Relevant Issues #1095

**Comment by Weltraumschaf** [comment]
IMHO this is not a good idea: Make and its dependencies is for development environments and installation (e.g. on prod envs) should not require development tools. So IMHO install should run merely standalone from any development tools. 

OTOH we can consider to introduce a `make install` target instead of `install.sh` which is a common installation method on Unix/Linux.

My personal preference is to provide artifacts for package managers: `apt install securecodebox`
