### ISSUE TITLE
Error when using defect-dojo hook: argument "content" is null 

### ISSUE THREAD

**Issue by Natali-Dubotolkova** [secureCodeBox/secureCodeBox#1552]
## Your Question

Good afternoon!

I searched for similar questions, but I didn't find them. I'm sorry if there has already been such a question.

I want to send the ZAP scan results to Defect Dojo. I get this error. 
![image](https://user-images.githubusercontent.com/45993009/212693139-825d175f-17aa-401c-a099-b06a30ffabfd.png)

![image](https://user-images.githubusercontent.com/45993009/212692631-95280857-c0d7-4e41-b1a8-8c87b93820bd.png)

**Comment by Natali-Dubotolkova** [comment]
I thought it was because it didn't see the results file, but as far as I can see, the file was successfully uploaded to minIO./
![image](https://user-images.githubusercontent.com/45993009/212721328-682eaddf-8db4-4555-9254-1f78a65034e1.png)

**Comment by J12934** [comment]
Hi @Natali-Dubotolkova 

From the logs it looks like the hook is unable to reach defectdojo itself, not s3.

DefectDojo can be abut tricky to set up correctly, especially with the hostnames (alternative host have to be set correctly otherwise defectdojo will refuse to answer the requests for that host name even when the networking routes it correctly).

We have a SCB + DefectDojo setup guide can you check if have everything configured correctly?

https://www.securecodebox.io/docs/how-tos/persistence-storage#defectdojo

**Comment by Natali-Dubotolkova** [comment]
@J12934 Thank you very much for the answer! 
When I sending the results to Defect-Dojo, nothing is written in the logs. I can assume that this is precisely for the reason that you wrote.
I'll try to check the configuration.
I sent requests to Defect Dojo using the api (/api/v2/import-scan/) - there were no problems.

**Comment by J12934** [comment]
Hey @Natali-Dubotolkova 
were you able to check if the configuration of the DefectDojo instance is correct and will properly respond to the hostname used by the DefectDojo Hook?

**Comment by Natali-Dubotolkova** [comment]
Hey @J12934 
Yes, the problem was that a signed certificate was needed. 
Thank you very much for your help!
