### ISSUE TITLE
Use of official Docker image for ssh-scanner

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#1730]
At the moment we use a self-built image because the official one had a bug. Since the official image seems to be fixed now, we should use it.

**Comment by Reet00** [comment]
@sofi0071 and I checked the offical docker [image](https://hub.docker.com/r/positronsecurity/ssh-audit). It is up to date now and gives the exact same output as before. 
However, the docker image is only updated with new releases (as we understood it). The last release was two years ago, all the issues fixed in the meantime where not in the docker image up until the latest release. 

Would it be disadvantage if the image does not get updated until the next release?
