### ISSUE TITLE
Inconsistent directory labeling for "ssh_scan"

### ISSUE THREAD

**Issue by SebieF** [secureCodeBox/secureCodeBox#180]
The directory ssh_scan is inconsistently using an underscore instead of a minus in comparison to other scanners (test-scan, kube-hunter), leading to a necessary workaround in the install script.

In general, ssh_scan is used as a path at the moment, whereas ssh-scan is used in the scantype and the tests.

Files and folders were ssh_scan is used:

![ssh_scanUsage](https://user-images.githubusercontent.com/32578476/97014007-0d4f5c00-154a-11eb-9397-916cf7402e3f.png)

**Comment by J12934** [comment]
It's written using an underscore as that is the official name of the tool https://github.com/mozilla/ssh_scan.

We've tried to use that name as much as possible. Some names (e.g. kubernetes and Helm names) don't allow underscores. That's why we've changed it there.

**Comment by fuhrmeistery** [comment]
I guess we can close this issue

**Comment by Weltraumschaf** [comment]
So when lot of tools do not allow underscores, why do we name it with underscore and add workarounds? The reason that the original name is with underscore is IMHO not a good reason. We can name it as we like. Eg. if the scanner is named ssh$scan we would rename it anyway because such.

So from architecture I strongly recommend renaming the directory althoug the scanner has _ in its original name.
