### ISSUE TITLE
🚓 New Security Scanner: Integrate SQLMap

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#187]
## New Scanner implementation request

**Is your feature request related to a problem? Please describe.**

As a security tester i would like to use the SQLMap Vulnerability Scanner to test against specific SQL Injections.

Allowing automating the process of detecting and utilizing SQL injection vulnerability in a website’s database, SQLMap is entirely free to use. The security testing tool comes with a powerful testing engine, capable of supporting 6 types of SQL injection techniques.

- WebSite: http://sqlmap.org/
- Source: https://github.com/sqlmapproject/sqlmap
- Docker: https://hub.docker.com/r/googlesky/sqlmap
- Container: `docker pull googlesky/sqlmap:latest` or `docker pull googlesky/sqlmap:latest-alpine`

**Describe the solution you'd like**

tbd.

**Describe alternatives you've considered**

**Additional context**

## Steps to implement a new scanner

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox/tree/master/scanners)
- [ ] Add a README.md and give a brief overview of the scanner and its configuration options.
- [ ] Implement a new scanner specific scan-type.yaml
- [ ] Implement a new scanner specific parse-definition.yaml
- [ ] Add (optional) some cascading-rules.yaml
- [ ] Add (optional) a Dockerfile for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage

**Comment by paulschmelzer** [comment]
Results on validating sqlmap for SCB:

Sqlmap is a session-based, interactive, hands on tool for finding and exploiting sql injections. The only reason to use it with SCB for automation would be the site url scan option. Compared to the OWASP ZAP scanner, sqlmap's site scanning is way less efficient because there is no Ajax spider and only GET url's with query parameteres and forms can be found.

Sqlmap is great for testing injections on specific parameters and actually exploiting a finding but not in a SCB setting.

Another reason why it won't work with SCB is that there is no way specifing an output file path, which is crucial for extracting results.

Therefore I see no useful reason to integrate sqlmap with SCB.
