### ISSUE TITLE
Make the istio annotation on jobs configurable

### ISSUE THREAD

**Issue by Michael-Kruggel** [secureCodeBox/secureCodeBox#2652]
### Is your feature request related to a problem?

Jobs don't function in clusters with STRICT mTLS.

### Describe the solution you'd like

The ability to overwrite the annotation that disables istio injection. This annotation: `sidecar.istio.io/inject = false`

### Additional context

This is running in a cluster that uses [UDS - Core](https://github.com/defenseunicorns/uds-core) which has an [application](https://github.com/defenseunicorns/pepr) that handles exiting the sidecar on jobs.

**Comment by J12934** [comment]
Hi @Michael-Kruggel 

generally I'd really like to get rid of annotation.
The context for why this was added is here: #132
The problem was that the scans never finished because the istio sidecar would never termiante.

If Istio has changed it's sidecar behavior to work with kubernetes jobs, e.g. by using the k8s 1.29 sidecar / initContainer restart always we should be able to just remove the annotation .

I'm not sure what the best way forward here is to support your environment where the sidecar termination is already handled. 
I'd rather remove the annotation (that is now set by default) and then allow people who want to disable the sidecar to set the annotation on their own and not have it set by default. This would be a breaking change though, we are planning to do a 5.0.0 breaking release in ~2 months so we could do it then.

**Comment by corang** [comment]
Given that the next breaking release isn't for "~2 months" would it be possible to make it configurable in the meantime? Leave the default as it is right now but allow the annotation value to be set?

**Comment by J12934** [comment]
Sure 😊
I'd suggest that we just add a "disableIstioSidecarsOnAllPods" helm value to the scb operator helm chart, which then passes this to the operator via an env var to then control if the annotation is passed to the pods or not. Ideally with a note that this flag is deprecated an will be removed with v5.

**Comment by J12934** [comment]
Will be resolved by the next release. Hopefully next week 🤞

PR: #2665
