### ISSUE TITLE
🚓 Integrate directory busting tool gobuster

### ISSUE THREAD

**Issue by twwd** [secureCodeBox/secureCodeBox#363]
### Is your feature request related to a problem

As a secureCodeBox user I would like to use [`gobuster`](https://github.com/OJ/gobuster) to find directories, subdomains, vhosts and open S3 buckets for consecutive scans.

### Describe the solution you'd like

`gobuster` is integrated into secureCodeBox.

### Describe alternatives you've considered

- [dirbuster](https://sourceforge.net/projects/dirbuster/) seems to be unmaintained, less performant and detects less categories of places.
- [dotdotpwn](https://github.com/wireghoul/dotdotpwn) is only specialized on traversing directory trees than finding new hosts and websites.

### Additional context

`gobuster` operates either for DNS, directories, S3 buckets or vhosts and requires a wordlist in the most cases.

## Steps to implement a new scanner
Hint: A general guide how to implement a new SCB scanner is documented [here](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner)

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox/tree/master/scanners)
- [ ] Add a `README.gotmpl` and give a [brief overview](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/readme) of the scanner and its configuration options.
- [ ] Add a HelmChart and document all configuration options.
- [ ] Implement a new scanner specific `scan-type.yaml`
- [ ] Implement a new scanner specific `parse-definition.yaml`
- [ ] Add (optional) some `cascading-rules.yaml` like documented [here](https://docs.securecodebox.io/docs/api/crds/cascading-rule)
- [ ] Add (optional) a `Dockerfile` for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage
- [ ] Add some example `scan.yaml` and `finding.yaml` files in the [example folder](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/examples-dir)
- [ ] Implement a [new integration or E2E test](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/integration-tests) for the hook [here](https://github.com/secureCodeBox/secureCodeBox/tree/master/tests/integration)

**Comment by Freedisch** [comment]
@Weltraumschaf, I would like to help on this if this issue is still active

**Comment by Weltraumschaf** [comment]
Hi @Freedisch, thanks for your offer.

At the moment we are reluctant to integrate new scanners because that automatically means that we have to maintain them. However, this issue comes from one of our core contributors, I will discuss this in the team.

Until then, you could try integrating this scanner yourself. The secureCodeBox can integrate any scanner container. This means that the code does not necessarily have to be in our repo.

There is already the idea of establishing community scanners: https://github.com/secureCodeBox/secureCodeBox/issues/915

**Comment by Freedisch** [comment]
> Hi @Freedisch, thanks for your offer.
> 

Alright, thanks for the reply. I will look into it

**Comment by Weltraumschaf** [comment]
Hi @Freedisch,

we discussed this issue in the team: Integration of Gobuster has very low priority for us at the moment because we think that this particular scanner is hard to automate. In our opinion Gobuster is a great tool for manual and custom penetration testing.

If you do an integration on your own, we'll add your repo to our documentation as a community scanner.

If you need some help, feel free to start a [discussion here](https://github.com/secureCodeBox/secureCodeBox/discussions) or join our channel "project-securecodebox" in the [OWASP Slack](https://owasp.org/slack/invite).

**Comment by Weltraumschaf** [comment]
We close this issue because we have no plans to add this scanner in the near future.
