### ISSUE TITLE
Starting scanner via CLI

### ISSUE THREAD

**Issue by wheelq** [secureCodeBox/secureCodeBox#81]
**error 500**
After running the zap scanner using CLI, curl comes back with error 500.

**To Reproduce**
1. issue scan as shown on the screenshot

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/1497172/55971834-2818f300-5c7a-11e9-8179-fa0b9dfcbae0.png)

**Comment by wheelq** [comment]
I get same even when I provide valid scanid (marked as successfull) using the swagger-ui.html

**Comment by wheelq** [comment]
I found the issue, but before applying the fix, why does cli submit HOST without protocol?

**Comment by rseedorff** [comment]
Hi @wheelq 
thanks for your hint and question. We have tried to implement the CLI in a more generic way, so that's easy to use and start some securityTests. 

For example (short version)
- `./run_scanner.sh zap https://some.system/somepath`
- `./run_scanner.sh nmap some.system`

The CLI script the tries to identify if the "target parameter" contains a protocol, a port or just an IP and uses this informations separately to configure the different security scanner. ZAP for example needs an URL as target parameter, Nikto needs an hostname and port...

In which case is the protocol missing, can you explain your usecase or CLI call a bit?

**Comment by wheelq** [comment]
Thanks @rseedorff 

zap.template.json looks like this:
![image](https://user-images.githubusercontent.com/1497172/56023630-3280ce80-5d06-11e9-9a2f-d87ed543170d.png)

After issuing scan (like in the first post), run_scanner.sh does the following:

`HOST_PORT=`echo ${TARGET} | sed 's!^https\?://!!g' | sed 's!/.*$!!g'` # hostname including user-provided port`
`HOST=`echo ${HOST_PORT} | sed 's!:.*$!!g'` # hostname only`

So HOST becomes just the hostname, without the http(s)://
And this, when passed to the scanner, fails with error 500. After I modified the run_scanner.sh and swapped HOST with TARGET, scans are running fine.

**Comment by fuhrmeistery** [comment]
Closed due to inactivity
