### ISSUE TITLE
Helm-docs CI job throws error messages

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#814]
## 🐞 Bug report
The helm docs CI job throws a lot of error messages:

![grafik](https://user-images.githubusercontent.com/1688580/141948043-b29d0517-6a36-4229-95f8-1a229cdb504b.png)

See for example [here](https://github.com/secureCodeBox/secureCodeBox/runs/4222060130?check_suite_focus=true). Assigning to @Ilyesbdlala for the moment, as I think he was the last one who worked with these things (and I am pretty sure it broke after we merged the changes to the SCB Bot) - feel free to reassign if you are the wrong person for this 😁.

**Comment by Ilyesbdlala** [comment]
I haven't made any changes to the `helm-docs.yaml` file that is responsible for this. So I dont see how the changes we merged would affect it. Shouldn't changes have been made to the `.helm-docs.gotmpl` files in "[Update Helm Docs seperatly ](https://github.com/secureCodeBox/secureCodeBox/commit/301d1439c68a9d6e01982b9f7dd3ec1bb5962ea9)" PR for the Helm Docs pipeline to work correctly?

**Comment by malexmave** [comment]
The PR you linked was just there to incorporate the helm docs changes that had not been automatically done in the PRs by EndPositive because the CI isn't running on external branches. So, it was triggering helm-docs changes on all future branches, and we wanted to reduce the amount of headache and merge conflicts in the future by quickly pulling in the doc changes in a separate PR and merging them. For this, @J12934 generated the docs locally (instead of just making an empty commit on a feature branch and triggering the CI) to speed things up a bit. 

So, the fact that helm-docs did not do anything on that branch is expected - but it should run on #806, for example (where the failing commands above are coming from), as I made changes to the CRDs there (and I think that should trigger changes by helm-docs? Or are the CRD docs maintained completely manually?).

**Comment by Ilyesbdlala** [comment]
Looking at the [Update Helm Docs](https://github.com/secureCodeBox/secureCodeBox/runs/3951330482) actions log, it seems the error you showed exists since at least 27 days (That's how far back I looked). I don't think it's an error. Maybe it just how it behaves when there's no new docs to change. Maybe @J12934 can shed some light here ?

**Comment by malexmave** [comment]
Hm, it may very well be the case that all my changes simply changed stuff that does not auto-generate its documentation.

Regardless, we should probably get around to fixing this error message at some point 😝.

**Comment by Ilyesbdlala** [comment]
The helm-docs job seems to work locally if we assign the shell used to `/bin/sh` instead of `/bin/bash`. an example on how to do this is : ``make docs SHELL=/bin/bash`` 
We regenerate the docs locally here #881 just to bring them up to date again.
However I don't know the consequences of changing the shell of our makefile. Maybe change it in only specific jobs ?
We can also maybe find a way around using the "read" command in the same way. That's where the issue wiht `/bin/sh` seems to be.

**Comment by RamiSouai** [comment]
Using SHELL=/bin/bash is not recommended since bash might not be install on the system and the path might change. 

Re-writing the makefile to be shell agnostic is the way to go!

**Comment by J12934** [comment]
Pull Request #886 has resolved this issue for GNU systems, still not working correctly for macOS / (BSD) systems 🤔

**Comment by J12934** [comment]
MacOS Issue is handled via #754
